name: AntiNbt
version: '0.3.1'
main: me.mynameisbob1928.antinbt.AntiNbt
api-version: '1.21.8'
author: mynameisbob1928
description: Anti nbt thing for 50xcreative so that the server doesn't die
permissions:
  antinbt.bypass:
    description: "AntiNbt bypass"
    default: op
  antinbt.nbtlog:
    description: "Logs in chat when someone tries to get a blocked item (must be explicitly assigned for effect)"
    default: false
